# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: minhtri1612
# "service" is the name of this project. This will also be added to your AWS resource names.
service: categoryService

provider:
  name: aws
  runtime: nodejs22.x
  region: ap-southeast-2

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get
resources:
  Resources:
    CategoryImageBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: category-image-ads-minhtri1612
        PublicAccessBlockConfiguration:
          BlockPublicAcls: false
          BlockPublicPolicy: false
          IgnorePublicAcls: false
          RestrictPublicBuckets: false
    CategoryTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Category
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: fileName
            AttributeType: S
        KeySchema:
          - AttributeName: fileName
            KeyType: HASH